k1LoW/deck

- cmd/ls.go
- deck/deck.go
This pull request introduces new functionality to list Google Slides presentations and includes several changes across multiple files to support this feature. The most important changes include adding a new command, defining a new `Slide` struct, and implementing the `List` method in the `Deck` struct.
New functionality for listing Google Slides presentations:
* [`cmd/ls.go`](diffhunk://#diff-9865f1c8ef620ff3656b04fb97f95e74a92261123bd6aa1b937e156131409ca7R1-R51): Added a new command `ls` to list Google Slides presentations. This includes the command definition and its associated logic to fetch and display the list of presentations.
Supporting changes in `deck` package:
* [`deck/deck.go`](diffhunk://#diff-65ff809baa1373e4a270791a6daba34bc71bfdc54bc35743b837451a3d17d1fbR49-R53): Defined a …
> feat: add `ls` command to list Google Slides presentations

- cmd/apply.go
- deck.go
This pull request includes several changes to the `cmd/apply.go` and `deck.go` files, mainly adding new functionalities and improving the code documentation. The most important changes include the addition of a new flag for updating the presentation title, new methods for listing layouts and updating the title, and improved code comments.
New functionality and improvements:
* [`cmd/apply.go`](diffhunk://#diff-a08f2011636c2b27ac4df1809b3bf95ee8aa9a6de2050807d33ddfb65fb69f6fR30-R31): Added a new flag `--title` (short `-t`) to specify the title of the presentation, and updated the `applyCmd` to handle this new flag. [[1]](diffhunk://#diff-a08f2011636c2b27ac4df1809b3bf95ee8aa9a6de2050807d33ddfb65fb69f6fR30-R31) [[2]](diffhunk://#diff-a08f2011636c2b27ac4df1809b3bf95ee8aa9a6de2050807d33ddfb65fb6 …
> feat(apply): add `--title` flag to update presentation title

- cmd/new.go
- deck.go
This pull request includes several changes to improve the functionality and structure of the `deck` package, particularly in the creation and management of Google Slides presentations. The most important changes include the addition of new commands, refactoring of the `Deck` struct, and improvements to the initialization and refresh processes.
* Added a new command `new` to create a new presentation, with options to set the title and use an existing presentation as a theme. (`cmd/new.go`)
* Refactored the `New` function to delegate initialization to a new `initialize` function and added `Create` and `CreateFrom` functions for creating presentations. (`deck.go`)
* Simplified the `ls` command by using the new `List` function from the `deck` package. (`cmd/ls.go`)
* Enhanced the `refresh` …
> feat(cmd): add `new` command to create presentations

- deck.go
- md/md.go
- testdata/slide.md
- testdata/slide.md.golden
This pull request includes several changes to the `deck` project, focusing on adding link support to fragments and updating test data accordingly.
Enhancements to fragment handling:
* [`md/md.go`](diffhunk://#diff-f10e982d75ada71772b6eea3f470a79ccdb670e48b51e202deb638bf61b80517R41): Added a `Link` field to the `Fragment` struct and updated the `toFragments` function to handle `ast.Link` nodes, allowing fragments to include links. [[1]](diffhunk://#diff-f10e982d75ada71772b6eea3f470a79ccdb670e48b51e202deb638bf61b80517R41) [[2]](diffhunk://#diff-f10e982d75ada71772b6eea3f470a79ccdb670e48b51e202deb638bf61b80517R191-R209)
Updates to slide processing:
* [`deck.go`](diffhunk://#diff-a39d05a55b005ceac781a85bfa8273ab035f2f66d982b0988d768405fddac3c3L432-R456): Modified the `applyPage` method to …
> feat: support link

- deck.go
This pull request includes several changes to the `applyPage` function in the `deck.go` file to enhance the handling of speaker notes and streamline the batch update process for slides. The most important changes are:
* Added logic to identify and verify the presence of speaker notes by iterating through `PageElements` and checking for `Placeholder.Type` set to "BODY". If no speaker notes are found, an error is returned.
* Added a new request to insert speaker notes text into the identified speaker notes object.
* Removed redundant batch update requests after setting titles and subtitles, consolidating them into a single request. [[1]](diffhunk://#diff-a39d05a55b005ceac781a85bfa8273ab035f2f66d982b0988d768405fddac3c3L359-L374) [[2]](diffhunk://#diff-a39d05a55b005ceac781a85bfa8273ab035f2f66d …
> feat(deck): add support for setting speaker notes

- deck.go
- md/md.go
- testdata/slide.md
- testdata/slide.md.golden
This pull request includes several changes to add support for italic text formatting in the `Deck` application. The most important changes include updating the `Fragment` struct to include an `Italic` field, modifying the `applyPage` function to handle italic text, and updating test data to reflect these changes.
Changes to support italic text formatting:
* [`md/md.go`](diffhunk://#diff-f10e982d75ada71772b6eea3f470a79ccdb670e48b51e202deb638bf61b80517R41): Updated the `Fragment` struct to include an `Italic` field and modified the `toFragments` function to set the `Italic` property based on the node level. [[1]](diffhunk://#diff-f10e982d75ada71772b6eea3f470a79ccdb670e48b51e202deb638bf61b80517R41) [[2]](diffhunk://#diff-f10e982d75ada71772b6eea3f470a79ccdb670e48b51e202deb638bf61b80517L197-R19 …
> feat: add support for italic text

- .gitignore
- deck.go
This pull request includes changes to the `applyPage` function in the `deck.go` file to improve handling of text styles. The most important changes include the introduction of a new variable to dynamically set the `Fields` value based on whether the text is bold or italic.
Improvements to text style handling:
* [`deck.go`](diffhunk://#diff-a39d05a55b005ceac781a85bfa8273ab035f2f66d982b0988d768405fddac3c3R426-R431): Added a new variable `fields` to dynamically set the `Fields` value to "bold" or "italic" based on the text style of the fragment.
* [`deck.go`](diffhunk://#diff-a39d05a55b005ceac781a85bfa8273ab035f2f66d982b0988d768405fddac3c3L438-R444): Updated the `Fields` assignment in the `UpdateTextStyleRequest` to use the new `fields` variable.
> fix(deck): correct text style update logic

- cmd/apply.go
- deck.go
- go.mod
- go.sum
- handler/dot/dot.go
This pull request introduces logging enhancements and new dependencies to the `deck` project. The most important changes include adding structured logging using the `slog` package, creating a custom `dot` handler for logging, and updating the `go.mod` file with new dependencies.
* [`cmd/apply.go`](diffhunk://#diff-a08f2011636c2b27ac4df1809b3bf95ee8aa9a6de2050807d33ddfb65fb69f6fR25-R30): Added structured logging with `slog` and a custom `dot` handler. The logger is initialized and set for the `Deck` instance. [[1]](diffhunk://#diff-a08f2011636c2b27ac4df1809b3bf95ee8aa9a6de2050807d33ddfb65fb69f6fR25-R30) [[2]](diffhunk://#diff-a08f2011636c2b27ac4df1809b3bf95ee8aa9a6de2050807d33ddfb65fb69f6fR53-R61)
* [`deck.go`](diffhunk://#diff-a39d05a55b005ceac781a85bfa8273ab035f2f66d982b0988d768405fddac3c …
> feat(logging): integrate slog for enhanced logging

- deck.go
This pull request includes changes to the `getHTTPClient` function in the `deck.go` file to modify the retry behavior of the HTTP client.
Changes to retry behavior:
* Increased the maximum number of retries from 5 to 10.
* Increased the maximum wait time between retries from 10 seconds to 30 seconds.
> fix(deck): increase retry limits for HTTP client

- README.md
- deck.go
- handler/dot/dot.go
- md/md.go
- md/md_test.go
- testdata/cap.md.golden
- testdata/freeze.md
- testdata/freeze.md.golden
This pull request introduces a new feature to freeze pages in the deck and includes various updates to support this functionality. Additionally, it improves logging and adds new test cases.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R137-R147): Added documentation for the new `freeze` feature, which allows skipping the operation of a target page.
* [`md/md.go`](diffhunk://#diff-f10e982d75ada71772b6eea3f470a79ccdb670e48b51e202deb638bf61b80517L17-R23): Updated the `Config` and `Page` structs to include the `Freeze` field, allowing pages to be marked as frozen. [[1]](diffhunk://#diff-f10e982d75ada71772b6eea3f470a79ccdb670e48b51e202deb638bf61b80517L17-R23) [[2]](diffhunk://#diff-f10e982d75ada71772b6eea3f470a79ccdb670e48b51e202deb638bf61b805 …
> feat: add freeze functionality to skip page modifications

- md/md.go
- testdata/freeze.md.golden
- testdata/slide.md.golden
This pull request includes changes to the `md` package to improve the handling of empty bodies in parsed pages and updates to related test data files. The most important changes include adding logic to remove empty bodies from parsed pages and updating the corresponding test data files to reflect this new behavior.
Improvements to handling empty bodies:
* [`md/md.go`](diffhunk://#diff-f10e982d75ada71772b6eea3f470a79ccdb670e48b51e202deb638bf61b80517R187-R198): Added logic in the `ParsePage` function to check for and remove empty bodies from the `page.Bodies` slice.
Updates to test data files:
* [`testdata/freeze.md.golden`](diffhunk://#diff-dc6e1d416a1e1060492e0cd2871f3e62990f4f95eedf2281e44ee1dee39fa1feL7-L18): Removed empty body objects from the test data to align with the new behavior …
> fix(md): remove empty bodies from parsed pages

- md/md.go
- md/md_test.go
- testdata/list_and_paragraph.md
- testdata/list_and_paragraph.md.golden
This pull request includes changes to improve the parsing and testing of markdown files. The most important changes include trimming whitespace and newline characters from fragment values, adding a new test case, and updating test data files accordingly.
Improvements to parsing:
* [`md/md.go`](diffhunk://#diff-f10e982d75ada71772b6eea3f470a79ccdb670e48b51e202deb638bf61b80517L171-R171): Modified the `ParsePage` function to trim whitespace and newline characters from fragment values.
Enhancements to testing:
* [`md/md_test.go`](diffhunk://#diff-a875d3534d9727c49cb3453f84caac0054354cf1d674fd78fd638afc7593ecf8R19): Added a new test case for parsing a markdown file with lists and paragraphs.
* [`testdata/list_and_paragraph.md`](diffhunk://#diff-467c9549ae265c11ba279bf3f1a55276abebe3bec062ff5d3b5 …
> fix(md): trim whitespace and newline characters from HTML Block fragment values

- deck.go
- md/md.go
- md/md_test.go
- testdata/bold_and_italic.md
- testdata/bold_and_italic.md.golden
This pull request includes changes to improve the handling of text fragments with bold and italic styles in the `Deck` and `md` packages. Additionally, new test cases and test data have been added to ensure the correct functionality.
Improvements to text fragment handling:
* [`deck.go`](diffhunk://#diff-a39d05a55b005ceac781a85bfa8273ab035f2f66d982b0988d768405fddac3c3L485-R490): Modified the `applyPage` function to use a slice for `fields` and join the slice elements into a string, ensuring both bold and italic styles can be applied simultaneously. [[1]](diffhunk://#diff-a39d05a55b005ceac781a85bfa8273ab035f2f66d982b0988d768405fddac3c3L485-R490) [[2]](diffhunk://#diff-a39d05a55b005ceac781a85bfa8273ab035f2f66d982b0988d768405fddac3c3L503-R504)
* …
> feat: support applying both bold and italic

- deck.go
This pull request includes a change to the `applyPage` function in the `deck.go` file. The change ensures that the placeholder for speaker notes is cleared before proceeding, which helps to avoid potential errors.
* [`deck.go`](diffhunk://#diff-a39d05a55b005ceac781a85bfa8273ab035f2f66d982b0988d768405fddac3c3R401-R403): Added a call to `d.clearPlaceholder(speakerNotesID)` within the `applyPage` function to clear the placeholder for speaker notes if it exists.
> fix(deck): clear placeholder for speaker notes in applyPage function

- deck.go
- go.mod
- go.sum
This pull request includes several changes to the `deck.go` file and updates to the `go.mod` file. The most important changes involve replacing the `open` package with the `browser` package and adding logic to handle token expiration and refreshing.
Package updates:
* Replaced `github.com/skratchdot/open-golang/open` with `github.com/pkg/browser` in the import statements (`deck.go`).
* Updated `go.mod` to replace `github.com/skratchdot/open-golang` with `github.com/pkg/browser` and added `github.com/google/go-cmp` as a new dependency [[1]](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R7-R10) [[2]](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L24).
Token handling improvements:
* Added logic to refresh the OAuth token …
> fix: support using refresh expired tokens

- deck.go
This pull request includes changes to the `deck.go` file to improve the handling of page layouts when applying markdown slides to a presentation. The most important changes include moving the logic for setting the default layout from the `Apply` method to the `applyPage` method.
Codebase simplification:
* [`deck.go`](diffhunk://#diff-a39d05a55b005ceac781a85bfa8273ab035f2f66d982b0988d768405fddac3c3L252-L261): Removed the logic for setting the default layout from the `Apply` method and moved it to the `applyPage` method to ensure the layout is set correctly when creating new pages. [[1]](diffhunk://#diff-a39d05a55b005ceac781a85bfa8273ab035f2f66d982b0988d768405fddac3c3L252-L261) [[2]](diffhunk://#diff-a39d05a55b005ceac781a85bfa8273ab035f2f66d982b0988d768405fddac3c3R328-R338)
> fix: apply default layout only when creating a new one

- cmd/apply.go
- deck.go
- md/md.go
- md/md_test.go
This pull request refactors the handling of slide data within the codebase by introducing a new `Slide` type in `deck.go` and replacing the older `Page` type from `md.go`. It also updates the processing of markdown files to use `Contents` instead of `Slides`. The changes aim to improve clarity and separation of concerns between the markdown parsing logic and the slide representation.
* Introduced a new `Slide` type in `deck.go` to represent slide data, including properties like `Layout`, `Freeze`, `Titles`, `Subtitles`, `Bodies`, and `SpeakerNote`. This replaces the older `Page` type. (`deck.go`, [deck.goR29-R71](diffhunk://#diff-a39d05a55b005ceac781a85bfa8273ab035f2f66d982b0988d768405fddac3c3R29-R71))
* Updated methods in `deck.go` to use the new `Slide` type instead of `md.Page`, …
> refactor: Introduce a new `deck.Slide` type

- cmd/apply.go
- handler/dot/dot.go
This pull request introduces a new `verbose` flag to the `apply` command and refines the logging behavior in the `dotHandler`. The most important changes include adding the `verbose` flag to the command-line interface, updating the conditional logic for logging, and improving the specificity of log message handling in the `dotHandler`.
* Added a new `verbose` flag (`-v`) to the `apply` command for enabling verbose output. This includes defining the flag in the `var` block, initializing it in the `init` function, and updating the condition to enable verbose logging when the flag is set. (`cmd/apply.go`: [[1]](diffhunk://#diff-a08f2011636c2b27ac4df1809b3bf95ee8aa9a6de2050807d33ddfb65fb69f6fR45) [[2]](diffhunk://#diff-a08f2011636c2b27ac4df1809b3bf95ee8aa9a6de2050807d33ddfb65fb69f6fL65-R66) …
> feat: add verbose flag and improve log message handling

- cmd/apply.go
- cmd/export.go
- cmd/new.go
- deck.go
This pull request introduces a significant refactor to ensure that all methods in the `Deck` package and related commands consistently use a `context.Context` parameter. This change improves context propagation, enabling better cancellation, deadlines, and tracing capabilities across the application. Below is a summary of the most important changes grouped by theme.
* Updated `cmd/apply.go`, `cmd/export.go`, and `cmd/new.go` to initialize `ctx` from `cmd.Context()` and pass it to all `Deck` methods. This ensures consistent context usage throughout command execution. [[1]](diffhunk://#diff-a08f2011636c2b27ac4df1809b3bf95ee8aa9a6de2050807d33ddfb65fb69f6fR60) [[2]](diffhunk://#diff-e54045fc1fa87e6c263ecf6b52cfb11d8cb7da5dcf3fd5ebceb681a3f98acf5cR39-R41) …
> fix: use context.Context

- deck.go
- md/md.go
- md/md_test.go
- testdata/code.md
- testdata/code.md.golden
Fix: https://github.com/k1LoW/deck/issues/87
Make it possible to parse inline code. However, no decoration.
> feat(md): add support for inline code fragments ( parse only )

- .gitignore
- Makefile
- md/md_test.go
This pull request introduces a new fuzz testing capability for the `Parse` function and updates the `Makefile` to include a new `fuzz` target. These changes aim to improve the robustness of the `Parse` function by testing it with a wide range of inputs.
* [`md/md_test.go`](diffhunk://#diff-a875d3534d9727c49cb3453f84caac0054354cf1d674fd78fd638afc7593ecf8R50-R88): Added a new fuzz test function `FuzzParse` that generates random inputs to test the `Parse` function. This ensures the function can handle unexpected or malformed inputs gracefully.
* [`Makefile`](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R23-R25): Added a new `fuzz` target under the build commands, which runs the fuzz test for the `Parse` function for a duration of 5 minutes. This integrates …
> test: add fuzzing test

- README.md
- md/md.go
- testdata/style.md
- testdata/style.md.golden
This pull request introduces changes to improve the handling of inline HTML elements in Markdown processing, updates documentation for better clarity, and fixes test cases to align with the new behavior. The most important changes include defining a list of allowed inline HTML elements, refining how closing tags and disallowed elements are handled, and updating test cases accordingly.
* [`md/md.go`](diffhunk://#diff-f10e982d75ada71772b6eea3f470a79ccdb670e48b51e202deb638bf61b80517R18-R23): Added a list of `allowedInlineHTMLElements` to restrict processing to specific inline HTML elements. Updated logic in `toFragments` to skip disallowed elements and reset the class attribute for closing tags. [[1]](diffhunk://#diff-f10e982d75ada71772b6eea3f470a79ccdb670e48b51e202deb638bf61b80517R18-R23) …
> fix(md): handle allowed inline HTML elements

- md/md.go
- md/md_test.go
- testdata/codeblock.md
- testdata/codeblock.md.golden
This pull request introduces support for parsing and handling code blocks in markdown content within the `md` package. The changes include adding a new `CodeBlock` type, updating the parsing logic to extract code blocks, and extending the test suite to validate the new functionality.
* **`md/md.go`:** Added a new `CodeBlock` struct to represent code blocks with optional language and value fields. Updated the `Content` struct to include a `CodeBlocks` field for storing parsed code blocks. Enhanced the `ParseContent` function to identify and handle both regular and fenced code blocks, extracting their language and content. [[1]](diffhunk://#diff-f10e982d75ada71772b6eea3f470a79ccdb670e48b51e202deb638bf61b80517R34-R47) [[2]](diffhunk://#diff-f10e982d75ada71772b6eea3f470a79ccdb670e48b51e202deb6 …
> feat(md): add support for code blocks in slide content

- README.md
- md/md.go
- testdata/codeblock.md.golden
This pull request introduces a key change to the terminology used for code block data, replacing "Value" with "Content" across the codebase. This improves clarity and aligns variable names with their intended meaning. The changes span documentation, code definitions, parsing logic, and tests.
* **Documentation (`README.md`)**: Updated references to code block data, replacing `CODEBLOCK_VALUE` with `CODEBLOCK_CONTENT` and `{{value}}` with `{{content}}`.
* **Struct Definition (`md/md.go`)**: Renamed the `CodeBlock` struct field from `Value` to `Content` for consistency.
* **Parsing Logic (`md/md.go`)**: Modified parsing functions to use `Content` instead of `Value` when handling code block data.
* **Environment Variables (`md/md.go`)**: Updated environment variable names to use …
> fix(md): rename `value` to `content` in code block

- deck.go
This pull request refines the handling of bullet points and text formatting in the `Deck` class within `deck.go`. The changes include introducing new helper functions, improving bullet range management, and enhancing text processing logic to support nested bullet points and style adjustments.
* **Refactored `bulletRange` struct**: Changed `start` and `end` fields from `int` to `int64` to support larger indices and ensure compatibility with other parts of the codebase.
* **Improved bullet range creation**: Added logic to handle nested bullet points and introduced a reverse sorting mechanism to ensure correct application order for bullet requests.
* **Introduced `getBulletPresetFromSlidesBullet` function**: Created a helper function to map `slides.Bullet` objects to `Bullet` presets based …
> feat: support bullet in shape

- deck.go
- handler/dot/dot.go
- integration_action_test.go
ref: https://github.com/k1LoW/deck/issues/149
This pull request refactors the `Deck` class in `deck.go` to improve code organization, enhance logging, and update method naming conventions. It also introduces visual feedback for specific log messages in the `dotHandler` and updates related tests in `integration_action_test.go`.
* Replaced private methods (`createPage`, `appendPage`, `insertPage`, `movePage`, `deletePage`) with public counterparts (`CreatePage`, `AppendPage`, `InsertPage`, `MovePage`, `DeletePage`) for better clarity and accessibility. [[1]](diffhunk://#diff-a39d05a55b005ceac781a85bfa8273ab035f2f66d982b0988d768405fddac3c3L151-R151) [[2]](diffhunk://#diff-a39d05a55b005ceac781a85bfa8273ab035f2f66d982b0988d768405fddac3c3L344-R358) …
> fix(deck): rename methods and add logging for page operations

- deck.go
This pull request introduces a logging enhancement in the `deck.go` file. The change modifies the behavior of the `Debug` method in the `apiLogger` struct to log certain messages as `Info` instead of `Debug` based on their content.
Logging behavior adjustment:
* [`deck.go`](diffhunk://#diff-a39d05a55b005ceac781a85bfa8273ab035f2f66d982b0988d768405fddac3c3R1901-R1910): Updated the `Debug` method in the `apiLogger` struct to check if the message starts with "retrying". If it does, the message is logged as `Info` instead of `Debug`. This adjustment is intended to display retry-related messages more prominently in the console, aiding visibility during operations.
> fix(deck): correct log levels for debug and warn messages

- logger/dot/dot.go
This pull request updates the visual representation of log messages in the `dotHandler` to improve clarity and provide more context for certain operations. The changes include replacing symbols for specific log messages and adding logic to handle directional movement for "moved page" events.
Updates to log message handling:
* [`logger/dot/dot.go`](diffhunk://#diff-458ebcb76d1a0720101a735727a244196a8419a8a2de9c9f7e0cfe630a8db880L53-R76): Changed the symbol for "deleted page" from `x` to `-` for consistency with other log messages.
* [`logger/dot/dot.go`](diffhunk://#diff-458ebcb76d1a0720101a735727a244196a8419a8a2de9c9f7e0cfe630a8db880L53-R76): Enhanced the "moved page" message by introducing logic to display directional arrows (`↓` or `↑`) based on the `from_index` and `to_index` …
> feat(logger): enhance dot handler for deleted/moved pages

- README.md
`silicon -l {{lang == "" ? "-l md" : "-l " + lang}}` results doubled option key `-l -l md` accidentally.
> docs: correct `-l` option usage

- action.go
- slide.go
This pull request refactors image comparison logic to improve efficiency and introduces new methods for handling image checksums and perceptual hashing. The most important changes include replacing JSON-based comparison with checksum-based comparison, adding new fields and methods to the `Image` struct, and updating image comparison logic to use these new methods.
* [`action.go`](diffhunk://#diff-655efec79154066c3d13d880da14f16b32e0a01d8d5703ddfd4177746c5f2c5cL875-R891): Replaced JSON-based comparison in `imagesEqual` with checksum-based comparison, ensuring more efficient and accurate handling of image equality. Added sorting of checksums before comparison to account for order differences.
* [`slide.go`](diffhunk://#diff-9b512ff450c4d8f204d811a69ae2ed95048d738c05504738d77a91bf3e9ade7cR82- …
> fix: cache calculated checksums and pHash values for image comparison

- md/md.go
This pull request improves the handling of image slices in the `ToSlides` method of the `md/md.go` file. The change simplifies the code by replacing the use of `copy` with `append` for combining slices.
Code simplification:
* [`md/md.go`](diffhunk://#diff-f10e982d75ada71772b6eea3f470a79ccdb670e48b51e202deb638bf61b80517L245-R245): Updated the `ToSlides` method to use `append` instead of `copy` for adding elements from `content.Images` to the `images` slice, ensuring proper handling of slice initialization and appending.
> fix(md): correct image copying logic in ToSlides

- deck.go
This pull request introduces a small but important change to the `ApplyPages` method in `deck.go`. The change ensures the presentation is refreshed before applying markdown slides to specified pages, improving reliability and error handling.
* [`deck.go`](diffhunk://#diff-a39d05a55b005ceac781a85bfa8273ab035f2f66d982b0988d768405fddac3c3R285-R287): Added a call to `d.refresh(ctx)` at the beginning of the `ApplyPages` method to refresh the presentation. If the refresh fails, an error is returned with a descriptive message.
> fix: respond when images are manually deleted in Google Slides

- deck.go
This pull request simplifies the `ApplyPages` method in `deck.go` by removing unnecessary code related to handling slide deletions.
Code simplification:
* [`deck.go`](diffhunk://#diff-a39d05a55b005ceac781a85bfa8273ab035f2f66d982b0988d768405fddac3c3L381-L386): Removed the call to `DeletePageAfter` and its associated logic, as it is no longer needed to handle cases where slides are reduced but not explicitly deleted through diff actions.
> refactor(deck): remove redundant DeletePageAfter call in ApplyPages function

- logger/dot/dot.go
This pull request introduces enhancements to the `dotHandler` in `logger/dot/dot.go` for improved logging functionality. The changes add support for displaying error messages in red when specific failure-related text is detected in log records.
* **Added red color formatting for error messages**: Introduced a `red` color formatter using `color.New(color.FgRed).SprintFunc()` to visually distinguish error messages. (`logger/dot/dot.go`, [logger/dot/dot.goR20](diffhunk://#diff-458ebcb76d1a0720101a735727a244196a8419a8a2de9c9f7e0cfe630a8db880R20))
* **Handling failure messages**: Updated the `Handle` method to check if a log record's message contains "failed to". If detected, the handler writes a red exclamation mark (`!`) to the output for emphasis. (`logger/dot/dot.go`, …
> feat(logger): add red color for failure messages

- cmd/apply.go
- deck.go
This pull request introduces changes to improve logging and refactor the handling of slide actions in the codebase. The most important changes include switching the logging format to JSON for better machine readability and introducing a new `actionDetail` type to simplify and structure the representation of slide actions.
* [`cmd/apply.go`](diffhunk://#diff-a08f2011636c2b27ac4df1809b3bf95ee8aa9a6de2050807d33ddfb65fb69f6fL70-R70): Updated the logging handler from `slog.NewTextHandler` to `slog.NewJSONHandler` to output logs in JSON format for improved readability and integration with logging systems.
* [`deck.go`](diffhunk://#diff-a39d05a55b005ceac781a85bfa8273ab035f2f66d982b0988d768405fddac3c3R85-R91): Added a new `actionDetail` type to encapsulate details about slide actions, including …
> feat(apply): switch to JSON logging when `--verbose` and enhance action details structure

- md/md.go
I thought it might be better to common the code around the env, but I added it straightforward for now.
> fix: add CODEBLOCK_CONTENT env to cmd

- README.md
- md/md.go
- md/md_test.go
- testdata/heading.md
- testdata/heading.md.golden
- Detect the minimum heading level in the document
- Use the detected level as title and level+1 as subtitle
close #187
There are almost no breaking changes! In fact, no changes have been made to existing test cases.
> feat: support dynamic heading levels for title detection

- README.md
- md/md.go
- md/md_test.go
- md/testdata/stub_code_img.go
- Added support for `{{output}}` template variable in `--code-block-to-image-command`
- Refactored code block image generation logic into the `genCodeImage` function
- Maintained backward compatibility by using stdout when the output file is not created
- Extract image generation logic from the `ToSlides` method into a standalone `genCodeImage` function
- Add `{{output}}` template variable that expands to a temporary file path
- Set `CODEBLOCK_OUTPUT` environment variable for consistency
- Add comprehensive tests using a stub image generator
close #203
> feat: Add {{output}} template variable support for code-block-to-image-command

- md/md.go
- md/md_test.go
- slide.go
- testdata/blockquote.md
- testdata/blockquote.md.golden
ref: #202 
This pull request introduces support for parsing and handling block quotes in markdown content, along with updates to the `deck` package to accommodate this new feature. The changes include modifications to the `Content` and `Slide` structures, the addition of a new `BlockQuote` type, and updates to the parsing logic and tests.
* [`md/md.go`](diffhunk://#diff-f10e982d75ada71772b6eea3f470a79ccdb670e48b51e202deb638bf61b80517R68): Added a `BlockQuotes` field to the `Content` struct and updated the `ParseContent` function to parse block quotes, flatten nested block quotes, and include them in the `Content` structure. [[1]](diffhunk://#diff-f10e982d75ada71772b6eea3f470a79ccdb670e48b51e202deb638bf61b80517R68) [[2]](diffhunk://#diff-f10e982d75ada71772b6eea3f470a79ccdb670e48b51e202deb63 …
> feat(md): add support for block quotes

- README.md
- md/md.go
- md/md_test.go
- testdata/ignore.md
- testdata/ignore.md.golden
- Support `` syntax to exclude pages from slide generation
This allows users to exclude draft pages, notes, or unwanted content from presentations while keeping them in the markdown file.
resolve #211
> feat: Add ignore page functionality with page configuration comment

- action.go
- compare.go
- deck.go
- integration_apply_test.go
- integration_test.go
This pull request refactors the comparison logic for slides and related entities, improves test output clarity, and fixes minor typos in the codebase. The most notable changes include moving comparison helper functions into a new file, enhancing the similarity scoring mechanism, and refining test thresholds and error handling.
* Moved comparison helper functions (e.g., `slidesEqual`, `titlesEqual`, `paragraphsEqual`) from `action.go` to a new file, `compare.go`, to improve modularity and maintainability. Introduced a `Compare` method for the `Slide` struct to encapsulate comparison logic.
* Updated `getSimilarity` in `action.go` to include block quote comparison, adding a scoring mechanism for block quotes to better evaluate slide similarity.
* Added a log statement to `TestApply` in …
> fix(compare): move comparison logic to a new file and simplify equality check

- compare.go
This pull request introduces a change to the `blockQuotesEqual` function in `compare.go` to ensure consistent ordering of `BlockQuote` slices before comparison. Sorting is implemented using a custom function that considers nesting level, paragraph count, and serialized paragraph content.
Enhancements to `blockQuotesEqual`:
* [`compare.go`](diffhunk://#diff-815e74c236b005371c72430760405deade20fe85ba02c7c75026ed5de790ee2eR116-R150): Added sorting logic to the `blockQuotesEqual` function using `slices.SortFunc`. The sorting criteria include nesting level, the number of paragraphs, and serialized paragraph content, ensuring consistent order for comparison. Error cases during JSON serialization are handled by treating the elements as unequal.
> feat(compare): add sorting logic for BlockQuotes in blockQuotesEqual function

- client.go
- deck.go
Since deck.go has become bloated, I will extract client.go. Also, the contents of the userAgent variable were incorrect (my mistake), so I fixed that as well.
> chore: add client.go and move http client related code into it

- deck.go
clearPlaceholder frequently caused errors, and those errors were being suppressed.
I realized that it was only necessary to clear the placeholder when text was inserted into it, so I made a correction to check before calling it.
This should prevent the errors from being suppressed.
This correction is a bit redundant, but I plan to make a more efficient correction later.
> fix clearPlaceholder

- compare.go
This pull request refactors the `imagesEqual` function in `compare.go` to ensure that the original slices of images remain unmodified during comparison by copying and sorting them into new slices before performing equality checks.
Refactoring for immutability:
* [`compare.go`](diffhunk://#diff-815e74c236b005371c72430760405deade20fe85ba02c7c75026ed5de790ee2eL99-R111): Updated the `imagesEqual` function to create copies of the input slices (`images1` and `images2`) before sorting them. This prevents unintended modifications to the original slices during the sorting process.
> fix(compare): ensure images are sorted without modifying input slices

- README.md
- cmd/open.go
- list.go
Add a new 'deck open' subcommand that opens the Google Slides presentation directly in the web browser. This improves the workflow by allowing users to quickly access their presentations without manually constructing URLs.
Usage:
- deck open deck.md - Opens presentation using ID from frontmatter
The command uses the system's default browser to open the presentation.
> feat: add 'open' subcommand to open Google Slides in browser

- apply.go
- deck.go
- integration_action_test.go
- logger/dot/dot.go
Currently, a request is issued and refreshed for each page deletion. However, since consecutive deletion requests can be sent as a single request, we have consolidated them.
Furthermore, Deck.DeletePage has been consolidated into the newly created DeletePages.
This should make the behavior of `--watch` more comfortable.
> perf: Batch delete pages

- action.go
- apply.go
- md/md.go
- slide.go
In code blocks, the aspect ratio and size are undefined, and it is important to display the entire image generated, so I would like to modify the image replacement method.
> feat: adjust imageReplaceMethod for code blocks

- action.go
- action_test.go
- apply.go
- compare.go
- integration_test.go
- preload.go
- slide.go
- slide_test.go
It is unclear under what conditions `Compare(a, b) bool` returns true, and it is common for Compare(a, b) int` to take three values, like the spaceship operator (`<=>`).
I renamed the `Compare` method and used the `slices` package to remove unnecessary functions and simplify the code.
> refactoring: compare.go

- cmd/apply.go
- cmd/export.go
- cmd/lsLayouts.go
- cmd/open.go
- integration_test.go
- md/cel.go
- md/frontmatter.go
- md/frontmatter_test.go
- md/md.go
- md/md_test.go
Currently, the `defaults` CEL is interpreted in `md.ToSlide`, but this process has the side effect of overwriting content.Layout. As a result, when `md.DiffContents` is called next, all overwritten pages are detected as diffs.
I resolved the issue by modifying `md.Parse` and `md.ParseFile` to accept a config parameter, and moving the CEL interpretation logic to the inside of `md.Parse`. 
This fix introduces a slight incompatibility in the function interface. Still, I believe this approach is preferable to exposing `md.ApplyConfig` publicly.
> fix: issue where all pages are listed as diff pages in DiffContents due to the `defaults` setting

- README.md
- config/config.go
- Configuration files should be placed under `XDG_CONFIG_HOME`
- Use `os.UserHomeDir` instead of the `$HOME` environment variable for cross-platform compatibility
- Fixed an issue where `XDG_*` was being overwritten each time, even though it appeared to be being referenced
- use `sync.OnceValue` to avoid race conditions and simplify code
This is incompatible, but I think the original implementation is incorrect.
I plan to add Windows support after this. @k1LoW
> fix: adjust configuration and data file placement rules

- helper_test.go
- integration_test.go
We launch the chrome process in advance and reuse it.
> chore: improv the efficiency of screenshot capture during testing

- .tagpr
- Makefile
- GO111MODULE=on is no longer needed
- Remove OSNAME, no longer used
- Remove ghch installation, no longer used
- BTW, you can use newer gh2changelog instead for similar needs
- Remove manual release tasks
- prerelease and release, we've used tagpr GitHub Actions instead
- Add `fulltest` and `install` tasks
- Update `.PHONY`
- 
I think you have your own way of doing things, so I would like to hear your opinion. @k1LoW
> chore: update and cleanup Makefile

- .github/workflows/integration.yml
- .gitignore
- helper_test.go
- integration_test.go
This PR enables integration tests to run on GitHub Actions using the service account functionality (#359) and folder ID specification feature (#354).
To avoid duplicate executions, manage costs, and address security concerns, the integration tests will run via:
- Manual trigger: workflow_dispatch for on-demand execution
- Weekly schedule: Mondays, early morning 5:36 JST (Sunday 20:36 UTC)
- Label trigger: When the "integration-test" label is added to a PR
- This enables testing for PRs from forked repositories
Authentication:
- Uses Workload Identity Federation for secure, keyless authentication
- No service account keys are stored in the repository
- Configuration values are hardcoded as they are not sensitive:
- workload_identity_provider
- service_account
- DECK_TEST_FOLDER_ID
I've …
> ci: introduce integration test on GitHub Actions

- README.md
- cmd/new.go
- config/config.go
Allow setting a default base presentation ID in the config file to reuse themes when creating new presentations automatically. The --from flag still takes precedence when both are present.
Also includes documentation updates and reorganization of the setup sections for better clarity.
**Note**: While there's some inconsistency between the configuration name `basePresentationID` and the `--from` flag, I chose `basePresentationID` because `fromPresentationID` sounds unnatural in English. We might consider adding the `--base` flag and deprecating the `--from` in the future for better consistency.
> feat: Add basePresentationID configuration for default theme reuse

- cmd/apply.go
ref: https://github.com/k1LoW/deck/pull/349
SSIA.
> fix: correct handling of `ignore` outside in non-watch mode.

- cmd/apply.go
- cmd/export.go
- cmd/lsLayouts.go
- cmd/new.go
- deck.go
HTTP client construction fails mostly when GCP credential is not configured.
This guide will improve deck first-timer experience.
> chore: guide users to doc when HTTP client is not constructed

- preload.go
To cancel the context, we must return an error, which results in duplicate error information, but we return the error here.
> chore: return error in uploading images for failfast

- cmd/new.go
Fix the issue where a deprecation warning is shown even though I'm using `--base` instead of `--from`.
> hide deprecation warning when using `--base`
