.gitignore
deck.go

fix: Use context instead of channel

---

deck.go
go.mod
go.sum

feat: open browser automatically for OAuth authentication

---

README.md
md/md.go

fix(md): handle leading horizontal line in markdown

---

deck.go
go.mod

fix(deck): reset bullet indices per body

---

cmd/apply.go
cmd/page_test.go
deck.go

fix: add `--page` option instead of `--start/end`

---

deck.go

fix: remove unnecessary newline

---

deck.go

fix(deck): clear text style before deleting paragraph bullets

---

deck.go

fix(deck): fix newline handling

---

deck.go

fix: handle missing auth code in getTokenFromWeb function

---

deck.go
deck_test.go
go.mod
go.sum
md/md_test.go
testdata/emoji.md
testdata/emoji.md.golden

feat(deck): add emoji-aware string counting ( does not support ligature )

---

deck.go
deck_test.go
go.mod
go.sum

fix(deck): count string as UTF-16

---

deck.go

This pull request introduces support for Proof Key for Code Exchange (PKCE) in the OAuth2 flow, improves code readability, and fixes a typo in the comments. The most important changes include the addition of PKCE-related functionality, adjustments to the OAuth2 flow to integrate PKCE, and minor improvements to the codebase.
* Added `generateCodeVerifier` and `generateCodeChallenge` helper functions to generate a code verifier and its corresponding challenge for PKCE. These functions ensure compliance with RFC7636. (`deck.go`, [deck.goR1016-R1034](diffhunk://#diff-a39d05a55b005ceac781a85bfa8273ab035f2f66d982b0988d768405fddac3c3R1016-R1034))
* Updated the OAuth2 flow in `getTokenFromWeb` to include PKCE parameters (`code_challenge` and `code_challenge_method`) in the authorization URL and …

feat(oauth): implement PKCE for enhanced security in OAuth flow

---

Makefile
deck.go
integration_test.go

fix(deck): add integration test

---

Makefile
action.go
action_test.go
deck_test.go
similarity_test.go

This pull request introduces several enhancements and fixes across multiple areas of the codebase, focusing on improving slide generation logic, similarity calculations, and test coverage. Key changes include reordering action generation for stability, refining similarity scoring, and expanding test cases to cover more scenarios. Additionally, minor refactoring and naming updates were made for clarity and consistency.
* Reordered action generation in `generateActions` to append slides before updating them, ensuring stable indices during updates (`action.go`, [action.goL73-R80](diffhunk://#diff-655efec79154066c3d13d880da14f16b32e0a01d8d5703ddfd4177746c5f2c5cL73-R80)).
* Adjusted `adjustShorterBefore` to preserve the original order of added slides by sorting indices before insertion …

fix: improve action generation and similarity scoring

---

.github/workflows/fuzz.yml

test: add fuzzing workflow

---

cmd/apply.go
integration_test.go
md/md.go
md/md_test.go

Revert "fix(md): introduce Parser struct for markdown parsing"

---

deck.go

This pull request introduces functionality to copy images from one slide to another when applying a page in the `Deck` struct. This enhancement ensures image elements are preserved during slide manipulation.
Key change:
* [`deck.go`](diffhunk://#diff-a39d05a55b005ceac781a85bfa8273ab035f2f66d982b0988d768405fddac3c3R441-R466): Added logic in the `applyPage` method to copy image elements from the current slide to the new slide using the `BatchUpdatePresentationRequest`. This includes creating image requests with properties like size, transform, and content URL, and executing the batch update via the `srv.Presentations.BatchUpdate` method.

feat(deck): add functionality to copy images between (create/delete) slides when update

---

cmd/apply.go
deck.go
go.mod
go.sum
handler/dot/dot.go

ref: #149 
This pull request introduces several enhancements and refactors to improve logging, error handling, and initialization within the `deck` project. Key changes include the addition of a spinner-based visual indicator in the `dotHandler`, refactoring the `Deck` initialization process to improve modularity, and implementing a custom API logger for better integration with `retryablehttp`.
* [`handler/dot/dot.go`](diffhunk://#diff-addbfc1f57ce506eabaa57742bfc6f9230832f210a82c0b47dc4bb0f1605aff6L22-R47): Enhanced the `dotHandler` to include a spinner for visual feedback during retries and added logic to stop the spinner when handling specific log messages. [[1]](diffhunk://#diff-addbfc1f57ce506eabaa57742bfc6f9230832f210a82c0b47dc4bb0f1605aff6L22-R47) …

feat(dot): display a spinner when retrying a Google Slides API call

---

action.go
cmd/root.go
config/config.go
deck.go
go.mod
go.sum
logger/dot/dot.go
md/md.go
slide.go

This pull request introduces several changes aimed at improving error handling, refactoring configuration management, and enhancing the maintainability of the codebase. The most significant updates include the addition of stack trace support for errors, the extraction of configuration paths into a dedicated package, and the consistent use of deferred error wrapping throughout the code.
* Added stack trace support to all error-returning functions using `errors.WithStack` for improved debugging. This change affects multiple functions across `action.go` and `deck.go`. [[1]](diffhunk://#diff-655efec79154066c3d13d880da14f16b32e0a01d8d5703ddfd4177746c5f2c5cL44-R50) [[2]](diffhunk://#diff-655efec79154066c3d13d880da14f16b32e0a01d8d5703ddfd4177746c5f2c5cL99-R109) …

feat: create error.json if deck fails

---

README.md

doc: use camelCase for frontmatter fields

---

cmd/apply.go

Sorry for the series of minor changes. In #226, the watch loop was optimized, but I was concerned about the possibility of a busy loop occurring. Since the Go compiler optimizes it, there is no major issue, and I have also confirmed that it works, but to be safe, I will use `time.After` to prevent the loop from running too many times.
This change also functions as a debounce process, as mentioned below, which is a nice bonus.
https://x.com/tadsan/status/1916708844958576759

perf: add debounce function to avoid busy loop while watching

---

.golangci.yml
deck.go

chore: add linter `funcorder`

---

action_test.go
deck.go

chore: use slices package to simplify code

---

deck.go

Fix: https://github.com/k1LoW/deck/issues/250

fix: does not copy images/shapes from markdown when update layout

---

deck.go

I have consolidated the UpdateTextStyleRequests for inline styles within the same range into a single request. This will slightly reduce the request size.
As mentioned in #255, it would be beneficial to allow fragments to retain information about their future display.
Therefore, consolidating them into one, as shown above, should be helpful in the future.

chore: Merge UpdateTextStyleRequest into one

---

cmd/new.go
md/frontmatter.go
md/frontmatter_test.go

fix case of presentationID

---

deck.go

If the layout derived from the default layout is deleted due to renaming or theme changes, an error will continue to occur during watch. Fixed to search for the default layout again when refreshing.
```json
{"time":"2025-07-18T16:07:28.331663+09:00","level":"ERROR","msg":"failed to apply changes","error":"failed to apply page: layout not found: \"タイトル スライド\""}
```

fix refresh; search defaultLayout again when disappering

---

deck.go

Fixed an error in clearPlaceholder in #270, so it can now be merged in a batchRequest.

chore: merge clear placeholder requests into batchUpdate request

---

action.go

SSIA. If there was a reason for not using the standard package, I apologize.

chore: use slices and cmp package to sort

---

md/md.go

fix(md): handle nil Frontmatter in ToSlides method

---

README.md
md/md.go
testdata/defaults.md
testdata/ignore.md.golden

This pull request introduces enhancements to the markdown-to-slides functionality, focusing on expanding the `defaults` configuration to include new actions, improving content handling logic, and refining the data structure for conditional actions. The key changes include support for new page actions (`freeze`, `ignore`, and `skip`), updates to the evaluation and application of these actions, and adjustments to the test cases to validate these features.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L126-R139): Updated the `defaults` field documentation to include new actions (`freeze`, `ignore`, `skip`) and clarified their functionality. Added examples for conditions and actions. …

feat: support `skip` `ignore` `freeze` for `defaults:`

---

apply.go
integration_apply_test.go

chore: reduce flaky tests

---

integration_test.go

SSIA again. The corrections were insufficient.

chore: fix flaky again

---

deck.go
deck_test.go

fix: correct profile name validation

---

README.md
cmd/apply.go
config/config.go
md/md.go
md/md_test.go

This pull request introduces support for global configuration files in the `deck` tool, enabling users to define default settings and conditional actions for presentations at an organization- or project-wide level. The changes include updates to the documentation, new configuration handling logic, and corresponding tests. Below are the key updates:
* Updated `README.md` to include details about global configuration files, their precedence, and an example configuration file. This explains how users can set global defaults for `breaks` and `defaults` fields and override them using frontmatter. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L135-R181) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R199-R208)
* …

feat: support config.yml for global setting

---

apply.go

I cleaned up a lot of unnecessary processing.

chore: tidy up ApplyPage

---

README.md
client.go
deck.go

chore: cleanup code and docs

---

style.go

chore: define d.getRequestForStyle for commonization and use it

---

apply.go
cmd/apply.go
deck.go

chore: display detailed API error message on debug logging

---

deck.go
preload.go

- Call SupportAllDrives properly in all locations
- Move files to trash when they cannot be deleted

fix: to work properly with Shared Drive

---

integration_action_test.go
integration_apply_test.go
integration_test.go
poolutil_test.go

chore: Define BuildTestOptions for debugging on testing

---

.github/workflows/tagpr.yml

ci: make tagpr work with workflow dispatch

---

apply.go

When adjusting the contents of a blockquote or when slides are re-rendered, text boxes are recreated and positioned at the top left, which is stressful, so we decided to reuse them when possible.
We reuse them when the number of quote blocks is the same. In most cases, I think there is only one quote block in a slide, so I think this is fine.

feat: reuse blockquote block if possible

---

action.go
apply.go

refactoring: add actionTypeSentinel to simplify code

---

apply.go
deck.go

refactoring: add a deck.fresh flag to reduce unnecessary requests

---

cmd/new.go

feat: add --base flag to new subcommand

---

action.go
action_test.go
integration_apply_test.go

fix: when slide pages are added or moved, the freeze option does not behave correctly.

---

compare.go
md/md.go
slide.go
testdata/blockquote.md.golden
testdata/br.md.golden
testdata/breaks_default.md.golden
testdata/breaks_enabled.md.golden
testdata/html_element_style.md.golden
testdata/list_and_paragraph.md.golden
testdata/paragraphs.md.golden
testdata/style.md.golden

refactoring: merge fragments in md package
